hw3 + hw4
danikkrapivnitskiy/AQA-JS_TS pull request #3
Opened 2024-05-30 14:17 UTC by danikkrapivnitskiy

2024-05-30 16:07 UTC, VladimirLQA requested changes

2024-05-30 16:07 UTC, VladimirLQA commented on hw_3/task_2.js
> +
Follow task description - Преобразовать Task 2 таким образом, чтобы значение НАПРИМЕР '2' (т.е. ЛЮБАЯ строка в которой лежит ТОЛЬКО ЦИФРА) пропускалось,
  преобразовываясь в number

2024-05-30 16:07 UTC, VladimirLQA commented on hw_3/task_3.html
> +        age = parseInt(age);
Have a look at the comment above

2024-05-30 16:07 UTC, VladimirLQA commented on hw_4/task_1.js
> +}
Pay attention to task description - `output from 10 to 0`

2024-05-30 16:07 UTC, VladimirLQA commented on hw_4/task_2.js
> +            console.log(bytes.toFixed(2) + " " + nameList[i]);
Rounded to 1 digit

2024-05-30 16:07 UTC, VladimirLQA commented on hw_4/task_3.js
> +for(i of word){
Explicit variable declaration

2024-05-30 16:07 UTC, VladimirLQA commented on hw_4/task_3.js
> +console.log(`word contains vowels: ${vowels_count}, and  consonants: ${consonants_count}`);
Try to test this example `ab21`

2024-05-30 20:28 UTC, VladimirLQA commented on hw_4/task_3.js
> +const str = 'aAbZzyZ';    // 'bBcAazA' for +1 and 'zZaYyxY' for -1
Try to modify this solution to handle such case ab 1Z - leave space and number in the result line

2024-05-31 04:05 UTC, VladimirLQA requested changes

2024-05-31 04:05 UTC, VladimirLQA commented on hw_4/task_3.js
> +consonants_count = 0
Explicit variables declaration, please

2024-05-31 04:05 UTC, VladimirLQA commented on hw_4/task_3.js
> +word("ab21")
With this solution I got such result - `word contains vowels: 1, and  consonants: 0`
but desired result is `word contains vowels: 1, and  consonants: 1`

2024-05-31 04:05 UTC, VladimirLQA commented on hw_4/task_3.js
> +	else if (typeof i === "symbol") {
I can't understand where we got or will get value of symbol type

2024-05-31 04:12 UTC, VladimirLQA commented on hw_3/task_3.html
> +        age = parseInt(age);
Use `isNaN` check with further conversion of the promt value for switch cases as in the previos task

2024-06-01 15:38 UTC, VladimirLQA requested changes

2024-06-01 15:38 UTC, VladimirLQA commented on JSTutorial/hw_4/task_1.js
> +}
Check the `step` part in this loop, had nothing in console, after runnig code

2024-06-01 15:38 UTC, VladimirLQA commented on JSTutorial/hw_4/task_2.js
> +            console.log(bytes.toFixed(2) + " " + nameList[i]);
Have to round the result to 1 number

2024-06-01 15:38 UTC, VladimirLQA commented on JSTutorial/hw_4/task_2.js
> +            console.log("Число делится и на 3 и на 5");
Add the value to console log that meet condition `15 - Число делится и на 3 и на 5`
Same for other cases

2024-06-01 15:38 UTC, VladimirLQA commented on JSTutorial/hw_4/task_3.js
> +		let word = wordSet.toLocaleLowerCase()
Why not use `toLowerCase()` ?

2024-06-01 15:38 UTC, VladimirLQA commented on JSTutorial/hw_5/task_1.js
> +function getEmployeeInfo(name) {
Add validation that passed argument should be a string type, if not throw an error

2024-06-01 15:38 UTC, VladimirLQA commented on JSTutorial/hw_5/task_2.js
> +function checkNotExistCompetitor(pizzaArray) {
Add validation that passed argument should be an array, if not throw an error
Same for other functions ....

2024-06-01 15:38 UTC, VladimirLQA commented on JSTutorial/hw_5/task_2.js
> +    for (let i of pizzaArray) {
```suggestion
    for (const i of pizzaArray) {
```

2024-06-01 15:38 UTC, VladimirLQA commented on JSTutorial/hw_5/task_2.js
> +    let maxCount = 0;
```suggestion
    let wordLength = 0;
```

2024-06-01 15:38 UTC, VladimirLQA commented on JSTutorial/hw_5/task_2.js
> +    for (let word of array) {
```suggestion
    for (const word of array) {
```

2024-06-01 15:38 UTC, VladimirLQA commented on JSTutorial/hw_5/task_2.js
> +    return largestWord.length > 0 ? largestWord : null
```suggestion
        if (word.length > wordLength) {
            largestWord = [word]
            wordLength = word.length;
        } else if (word.length == wordLength) { 
             largestWord.push(word);
         }
    }
    
    return largestWord.length > 0 ? largestWord : null
```

2024-06-01 15:38 UTC, VladimirLQA commented on JSTutorial/hw_5/task_2.js
> +        if (!newArray.includes(symbol) && !isNaN(symbol)) {
```suggestion
        if (!newArray.includes(symbol)) {
```
Just remove elements that appear two and more times

2024-06-01 15:38 UTC, VladimirLQA commented on JSTutorial/hw_5/task_2.js
> +    return isEqual;
```suggestion
    const reversedArray = arr.slice().reverse();
    for (let i = 0; i < arr.length / 2; i++) {
        if (arr[i] !== reversedArray[i]) {
           return false;
        }
    }
    return true;
```

Divide the arr.length to make less iterations simplify returns

2024-06-01 15:49 UTC, danikkrapivnitskiy commented on JSTutorial/hw_4/task_2.js
> +            console.log(bytes.toFixed(2) + " " + nameList[i]);
why? result rounding 98798769786 is 98.80 -> correct

2024-06-01 16:46 UTC, VladimirLQA commented on JSTutorial/hw_4/task_2.js
> +            console.log(bytes.toFixed(2) + " " + nameList[i]);
from task description
Результат должен быть округлен до 1 знака после запятой методом .toFixed(), про который надо почитать самим ;)

2024-06-02 06:54 UTC, VladimirLQA commented on JSTutorial/hw_5/task_1.js
> +    if (!isNaN(name)) {
```suggestion
    if (typeof name === 'string') {
```

2024-06-02 06:57 UTC, VladimirLQA commented on JSTutorial/hw_4/task_3.js
> +		} else if (isNaN(i)) {
Add the string that contains consonants and do `.includes(i)` check
`isNaN` would not work with special characters as `#, $` etc.

2024-06-02 06:58 UTC, VladimirLQA approved these changes

2024-06-02 08:00 UTC, merged