first_branch
danikkrapivnitskiy/AQA-JS_TS pull request #4
Opened 2024-06-09 13:16 UTC by danikkrapivnitskiy

2024-06-09 16:18 UTC, VladimirLQA requested changes

2024-06-09 16:18 UTC, VladimirLQA commented on JSTutorial/hw_6/task_2.js
> +  const sentenseStr = "I am the best AQA ever!";
Pay attention to task discription
`Преобразуйте строку таким образом, 
  чтобы вместо каждой буквы была цифра, показывающая сколько раз эта буква встречается в предложении.`

2024-06-09 16:18 UTC, VladimirLQA commented on JSTutorial/hw_6/task_2.js
> +  console.log(...mapToNumber);
We already know how to use functions, so it's time to use them :)

2024-06-09 16:18 UTC, VladimirLQA commented on JSTutorial/hw_6/task_2.js
> +  const avgPrice = prices.reduce((result, number) => result += number / prices.length, 0).toFixed(2);
The description does not mention float value as a result

2024-06-09 16:18 UTC, VladimirLQA commented on JSTutorial/hw_6/task_2.js
> +  const words = ["sdfsdfsdfaaa", "lknjckbvhjibeiru", "oiusdfi"]
Use function syntax

2024-06-09 16:18 UTC, VladimirLQA commented on JSTutorial/hw_6/task_2.js
> +    if (afterMap[i][1] >= max) {
In this way you do not sort them, in the result I got same position for each word as it was
Try to run this case, for clarity
`const words = ['aai3', 'afd1', 'fsou2']`

2024-06-09 16:18 UTC, VladimirLQA commented on JSTutorial/hw_6/task_2.js
> +const arr = [[['(']], ')', '(', ')', ')', ['(', ['('], [')']]]
Use function syntax :)

2024-06-09 19:25 UTC, anatoly-karpovich approved these changes

2024-06-09 19:25 UTC, anatoly-karpovich commented on JSTutorial/hw_6/task_3.js
> +    .map(x => x - 1);
```suggestion
     .find((num, i, arr) => arr.indexOf(num) !== (num - 1)) - 1
```

2024-06-12 11:09 UTC, danikkrapivnitskiy commented on JSTutorial/hw_6/task_2.js
> +const arr = [[['(']], ')', '(', ')', ')', ['(', ['('], [')']]]
I did it, no?

arr.flat(Infinity).map(symbol => symbol === ")" ? count++ : count--);

2024-06-12 11:11 UTC, danikkrapivnitskiy commented on JSTutorial/hw_6/task_2.js
> +    if (afterMap[i][1] >= max) {
result it : [ 'fsou2', 'afd1', 'aai3' ]

2024-06-14 03:03 UTC, merged